name: Validate integration

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: "actions/checkout@v2"

      - name: validate
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: "actions/checkout@v2"

      - name: validate
        uses: "hacs/action@main"
        with:
          category: "integration"
