---
name: "Keep workflows alive"
# yamllint disable-line rule:truthy
on:
  schedule:
    # run once a month on the first day of the month at 00:20 UTC
    # - cron: '20 0 1 * *'
    - cron: '0/30 * * * *'
  workflow_dispatch: {}

jobs:
  keepalive:
    name: Keep workflows alive
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repos: ${{ github.repository }}