name: Lint

on: [push, pull_request]

jobs:
  python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.2
      - uses: isort/isort-action@master
      - uses: psf/black@stable
